import { Geist, Geist_Mono } from "next/font/google";
import "./main.css";
import Header from "@/Component/Header";
import Footer from "@/Component/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Blogger",
  description: "Generated by create next app",
  authors: [{name: "Vishwanath Nandakishore"}],
  robots:{index: true, follow: true,}
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
